# Form implementation generated from reading ui file 'datosEnemigo.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgDatosEnemigo(object):
    def setupUi(self, dlgDatosEnemigo):
        dlgDatosEnemigo.setObjectName("dlgDatosEnemigo")
        dlgDatosEnemigo.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgDatosEnemigo.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=dlgDatosEnemigo)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 90, 181, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblNombreEnemigo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblNombreEnemigo.setObjectName("lblNombreEnemigo")
        self.verticalLayout_3.addWidget(self.lblNombreEnemigo)
        self.lblVidaEnemigo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblVidaEnemigo.setObjectName("lblVidaEnemigo")
        self.verticalLayout_3.addWidget(self.lblVidaEnemigo)
        self.lblAtaqueEnemigo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblAtaqueEnemigo.setObjectName("lblAtaqueEnemigo")
        self.verticalLayout_3.addWidget(self.lblAtaqueEnemigo)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txtNombreEnemigo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.txtNombreEnemigo.setObjectName("txtNombreEnemigo")
        self.verticalLayout_2.addWidget(self.txtNombreEnemigo)
        self.txtVidaEnemigo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.txtVidaEnemigo.setObjectName("txtVidaEnemigo")
        self.verticalLayout_2.addWidget(self.txtVidaEnemigo)
        self.txtAtaqueEnemigo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.txtAtaqueEnemigo.setEnabled(True)
        self.txtAtaqueEnemigo.setObjectName("txtAtaqueEnemigo")
        self.verticalLayout_2.addWidget(self.txtAtaqueEnemigo)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(dlgDatosEnemigo)
        QtCore.QMetaObject.connectSlotsByName(dlgDatosEnemigo)

    def retranslateUi(self, dlgDatosEnemigo):
        _translate = QtCore.QCoreApplication.translate
        dlgDatosEnemigo.setWindowTitle(_translate("dlgDatosEnemigo", "Dialog"))
        self.lblNombreEnemigo.setText(_translate("dlgDatosEnemigo", "TextLabel"))
        self.lblVidaEnemigo.setText(_translate("dlgDatosEnemigo", "TextLabel"))
        self.lblAtaqueEnemigo.setText(_translate("dlgDatosEnemigo", "TextLabel"))
        self.txtNombreEnemigo.setText(_translate("dlgDatosEnemigo", "Nombre:"))
        self.txtVidaEnemigo.setText(_translate("dlgDatosEnemigo", "Vida:"))
        self.txtAtaqueEnemigo.setText(_translate("dlgDatosEnemigo", "Ataque:"))
