# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(362, 332)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDatosHeroe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDatosHeroe.setGeometry(QtCore.QRect(70, 20, 81, 17))
        self.btnDatosHeroe.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.btnDatosHeroe.setObjectName("btnDatosHeroe")
        self.btnDatosEnemigo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDatosEnemigo.setGeometry(QtCore.QRect(70, 70, 81, 17))
        self.btnDatosEnemigo.setObjectName("btnDatosEnemigo")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 18))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.btnDatosHeroe.setText(_translate("mainWindow", "Datos Heroe"))
        self.btnDatosEnemigo.setText(_translate("mainWindow", "Datos Enemigo"))
